apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-demo-dev
resources:
- ../../base
patchesStrategicMerge:
- patch-deployment.yaml
- secret-sonar-login.yaml
#images:
  # - name: app-api
  #   newName: image-registry.openshift-image-registry.svc:5000/app-demo-dev/app-api
  #   newTag: "1.0.0-SNAPSHOT"