apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
spec:
  template:
    spec:
      containers:        
        - name: app-api
          image: image-registry.openshift-image-registry.svc:5000/app-demo-dev/app-demo:1.0.0-SNAPSHOT