apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/app
- ../../base/h2
- ../../base/liquibase
# - sealedsecret-secret-db.yaml
patchesStrategicMerge:
- patch-configmap-properties-api.yaml
- patch-buildconfig-liquibase.yaml
- patch-deployment.yaml
configMapGenerator:
- name: liquibase-changelogs
  behavior: merge
  files:
  - changelog/master.xml
images:
  # - name: app-api
  #   newName: image-registry.openshift-image-registry.svc:5000/app-demo-test/app-api
  #   newTag: "1.0.0-SNAPSHOT"
  - name: h2
    newName: image-registry.openshift-image-registry.svc:5000/app-demo-pre/h2
    newTag: "latest"
  - name: liquibase
    newName: image-registry.openshift-image-registry.svc:5000/app-demo-pre/liquibase
    newTag: "latest"
